Feature/fp2
saparjohnick/study pull request #4
Opened 2021-10-26 16:43 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/74/practices/1103 
also done [rackup](https://github.com/fullstack-expert/study/tree/master/test/exercise/rackup) task

2021-11-01 13:19 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +          array = drop(1) # don't count first element
Давай попробуем реализовать без мутации переменных

2021-11-01 13:19 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        unless acc.present?
Вместо unless старайся использовать if для читабельности. Ruby дает нам такие методы как .nil? и .blank?, которые в этом случае можно использовать с if.

2021-11-01 13:19 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +          array = drop(1) # don't count first element
В случае с массивом посмотри в сторону splat оператора

2021-11-01 13:19 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        my_each(i += 1, &block)
Можно избавится от индексов, передавая на каждом шаге подмассив

2021-11-04 21:09 UTC, saparjohnick commented
переписал без индексов и unless-конструкций https://github.com/saparjohnick/study/pull/4/commits/0d86aca1a83a8a0529a1bd2d02819d7d2f860813

2021-11-06 17:53 UTC, Andrew8xx8 requested changes

2021-11-06 17:53 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_each(&block)
`each` нужно реальзовать используя рекурсию

2021-11-06 17:53 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_each do |num|
`each` нужно реальзовать используя рекурсию. В данном случае да, код работает, но он игнорирует суть ФП, т.к. блок который передается в each использует acc по принципу замыкания, а значит имеет побочный эффект, и не является чистой функцией

2021-11-06 21:25 UTC, saparjohnick commented
@Andrew8xx8 Спасибо! Отрефакторил здесь https://github.com/saparjohnick/study/commit/89497023cc9ba008a71dc580e7a25b53ed3b91eb (так же с учетом фидбека от @moklidia )

Неправильно прочел, что нужно было изменить здесь https://github.com/saparjohnick/study/pull/4/commits/774b5c469db48a5faca8847eb01eff2976517fe1 из-за чего заменил реализацию с рекурсией на обычную

2021-11-07 14:15 UTC, moklidia requested changes

2021-11-07 14:15 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        starts_at += 1
Функциональное программирование не подразумевает переопределение (мутацию) переменных.

2021-11-07 14:15 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        starts_at += 1
Мутация

2021-11-07 18:10 UTC, saparjohnick commented
@moklidia  https://github.com/saparjohnick/study/pull/4/commits/aebbcdb7a327147cdb898c9fe808cdb8407ce021 ?)

2021-11-07 18:13 UTC, saparjohnick commented
@moklidia  https://github.com/saparjohnick/study/pull/4/commits/14bcb75a0dce9f6452aa8cc1d5ba2f011b55ecaa ?)

2021-11-08 06:45 UTC, moklidia requested changes

2021-11-08 06:45 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        my_reduce(1) do |acc, el|
Зачем ы инициализируешь аккумулятор единицей? Ты можешь инициализировать его MyArray.new

2021-11-09 06:29 UTC, moklidia approved these changes

2021-12-01 18:20 UTC, merged